using System.Text.Json;
using Lumen.Core.Paths;
using Lumen.Core.Quality;

namespace Lumen.Core.Host;

public static class SunshineConfigWriter
{
    /// <summary>
    /// Apollo/Sunshine conf. Virtual display Hz comes from the client request;
    /// dd_refresh_rate_option=auto applies it. Privacy uses ensure_only_display
    /// (virtual display on, physical monitors off).
    /// </summary>
    public static string Render(StreamProfile profile)
    {
        var dd = profile.PrivacyMode ? "ensure_only_display" : "ensure_primary";
        var hevc = profile.Quality == QualityMode.SharpLan ? 3 : 0;
        var av1 = profile.Quality == QualityMode.SharpLan ? 3 : 0;
        var nvencPreset = profile.Quality == QualityMode.SharpLan ? 3 : 1;
        var upnp = profile.Wan.EnableUpnp ? "enabled" : "disabled";
        var external = string.IsNullOrWhiteSpace(profile.Wan.ExternalIp)
            ? ""
            : $"external_ip = {profile.Wan.ExternalIp}{Environment.NewLine}";
        var wanEnc = profile.Wan.EnableStun || profile.Wan.EnableUpnp ? 1 : 0;

        return $"""
            # Generated by Lumen Stream. GPL-3.0-or-later.
            sunshine_name = {profile.HostName}
            min_log_level = info
            log_path = {ToConfPath(LumenPaths.HostLogFile)}
            file_apps = {ToConfPath(LumenPaths.HostAppsFile)}
            origin_web_ui_allowed = {(profile.Wan.EnableUpnp || profile.Wan.EnableStun ? "wan" : "pc")}
            port = {profile.Wan.HostPort}
            file_state = {ToConfPath(LumenPaths.HostStateFile)}
            credentials_file = {ToConfPath(LumenPaths.HostCredentialsFile)}

            # Advertise high-refresh so 144/165/240 are first-class, not hidden.
            fps = [30,60,90,120,144,165,240]
            resolutions = [
              1280x720,
              1920x1080,
              2560x1440,
              3840x2160
            ]

            # Match client resolution and Hz on the (virtual) display.
            dd_configuration_option = {dd}
            dd_resolution_option = auto
            dd_refresh_rate_option = auto
            dd_hdr_option = {(profile.EnableHdr ? "auto" : "disabled")}
            isolated_virtual_display_option = {(profile.PrivacyMode ? "enabled" : "disabled")}
            max_bitrate = {profile.BitrateKbps}

            hevc_mode = {hevc}
            av1_mode = {av1}
            nvenc_preset = {nvencPreset}
            nvenc_twopass = disabled
            nvenc_latency_over_power = enabled
            fec_percentage = 20
            min_threads = 2

            controller = enabled
            gamepad = auto
            mouse = enabled
            keyboard = enabled
            native_pen_touch = {(profile.NativePenTouch ? "enabled" : "disabled")}
            high_resolution_scrolling = enabled

            upnp = {upnp}
            address_family = both
            lan_encryption_mode = 0
            wan_encryption_mode = {wanEnc}
            {external}# monitors requested by Lumen: {profile.MonitorCount} (see lumen-displays.json + apps.json)
            """;
    }

    public static void Write(StreamProfile profile)
    {
        LumenPaths.EnsureLayout();
        File.WriteAllText(LumenPaths.HostConfigFile, Render(profile));
        File.WriteAllText(LumenPaths.DisplaysFile, JsonSerializer.Serialize(new
        {
            monitors = profile.MonitorCount,
            privacyMode = profile.PrivacyMode,
            fps = profile.Fps,
            width = profile.Width,
            height = profile.Height
        }, new JsonSerializerOptions { WriteIndented = true }));
        File.WriteAllText(LumenPaths.WanFile, JsonSerializer.Serialize(profile.Wan, new JsonSerializerOptions { WriteIndented = true }));
    }

    private static string ToConfPath(string path) => path.Replace('\\', '/');
}
