<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>Lumen.Launcher</RootNamespace>
    <AssemblyName>Lumen</AssemblyName>
    <ApplicationIcon />
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lumen.Core\Lumen.Core.csproj" />
  </ItemGroup>
</Project>
